swagger: "2.0"
info:
  description: "This is the documentiation for gaelo_processing"
  version: "0.1"
  title: "Gaelo_processing"
  contact: 
    email: "Salim.kanoun@gmail.com"
tags:
- name: "radiomics"
  description: "Radiomics results"
- name: "images"
  description: "Handle the images"
- name: "masks"
  description: "Handle the masks"
- name: "models"
  description: "Datas from models"
paths:
  /models/<str:model_name>/metadata:
    get:
      tags:
      - "models list"
      summary: "Get models metadata list"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        schema:
          $ref: "#/definitions/Models"
      responses:
        "404":
          description: "No models found"    
definitions:
  Models:
    type: "object"
    properties:
      lsit:
        type: "list"