swagger: "2.0"
info:
  description: "This is the documentiation for gaelo_processing"
  version: "0.1"
  title: "Gaelo_processing"
  contact: 
    email: "Salim.kanoun@gmail.com"
tags:
- name: "radiomics"
  description: "Radiomics results"
- name: "images"
  description: "Handle the images"
- name: "masks"
  description: "Handle the masks"
- name: "models"
  description: "Datas from models"
paths:
  /images:
    post:
      tags:
      - "image"
      summary: "Create an image"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        schema:
          $ref: "#/definitions/Image"
      responses:
        "404":
          description: "Image not created"
    get:
      tags:
      - "image"
      summary: "Get an image id"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        schema:
          $ref: "#/app/gaelo_processing/controller/image_controller"
      responses:
        "404":
          description: "No image found"
definitions:
  Image:
    type: "object"
    properties:
      id:
        type: "string"